name: Validate Commit Messages

on:
  push:
    branches:
      - main

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate commit messages
      run: |
        COMMIT_MSG=$(git log --format=%B -n 1 $GITHUB_SHA)

        if [[ $COMMIT_MSG =~ correo|mantis ]]; then
          echo "Commit message is valid."
        else
          echo "Commit message does not contain required keywords (correo|mantis)."
          exit 1
        fi
